apiVersion: test.openstack.org/v1beta1
kind: Tempest
metadata:
  name: tempest-tests-designate
  namespace: openstack
spec:
  networkAttachments:
    - ctlplane
    #- designateext
  containerImage: quay.io/podified-antelope-centos9/openstack-tempest-all:current-podified
  storageClass: lvms-local-storage
  tempestRun:
    includeList: |
      designate_tempest_plugin.tests.api.v2.*
      #designate_tempest_plugin.tests.scenario.v2.*
      #designate_tempest_plugin.tests.*
    concurrency: 4
    externalPlugin:
      - repository: "https://opendev.org/openstack/designate-tempest-plugin.git"
        #changeRepository: "https://review.opendev.org/openstack/octavia-tempest-plugin"
        #changeRefspec: "refs/changes/64/897564/29"
  tempestconfRun:
    overrides: |
      DEFAULT.use_stderr true
      #dns.nameservers 172.50.0.81:53,172.50.0.80:53
      #designate.nameservers 172.50.0.81:53,172.50.0.80:53
      dns.nameservers '172.34.0.80:53,172.34.0.81:53,172.34.0.82:53'
      designate.nameservers '172.34.0.80:53,172.34.0.81:53,172.34.0.82:53'
      dns_feature_enabled.api_v2_quotas true
      dns_feature_enabled.api_v2_root_recordsets true
      dns_feature_enabled.api_admin true
      dns_feature_enabled.api_v2 true
      dns_feature_enabled.api_v2_quotas_verify_project true
      dns_feature_enabled.enforce_scope false
      dns_feature_enabled.enforce_new_defaults false
      #enforce_scope.designate false
      enforce_scope.designate false
