apiVersion: test.openstack.org/v1beta1
kind: Tempest
metadata:
  name: tempest-neutron-dns-tests
  namespace: openstack
spec:
  #containerImage: images.paas.redhat.com/podified-rhos18-rhel9/openstack-tempest-all:e306c000e14953ee40577a3ec3758f23
  containerImage: images.paas.redhat.com/podified-rhos18-rhel9/openstack-tempest-all:3197eaafa1b5916f3b3bcd653bb4f25c
  networkAttachments:
  - ctlplane
  openStackConfigMap: openstack-config
  openStackConfigSecret: openstack-config-secret
  privileged: true
  storageClass: lvms-local-storage
  SSHKeySecretName: test-operator-controller-priv-key
  tempestconfRun:
    create: true
    deployerInput: |
      [enforce_scope]
      neutron = true
      keystone = true
      nova = true
      glance = true
      barbican = false
      cinder = false
      designate = true
      ironic = false
      ironic_inspector = false
      octavia = false
      manila = false
      placement = false
      [identity-feature-enabled]
      enforce_scope = true
    overrides: |-
      auth.admin_domain_name Default
      auth.admin_project_name admin
      auth.admin_username admin
      compute-feature-enabled.vnc_console 'True'
      neutron_plugin_options.advanced_image_flavor_ref 22222222-2222-2222-2222-222222222222
      neutron_plugin_options.advanced_image_ref 11111111-1111-1111-1111-111111111111
      neutron_plugin_options.advanced_image_ssh_user 'cloud-user'
      neutron_plugin_options.available_type_drivers 'vlan'
      neutron_plugin_options.create_shared_resources true
      neutron_plugin_options.firewall_driver ovn
      neutron_plugin_options.is_igmp_snooping_enabled true
      neutron_plugin_options.global_ip_address '1.1.1.1'
      validation.run_validation true
      whitebox_neutron_plugin_options.node_tunnel_interface eth1
      whitebox_neutron_plugin_options.proxy_host_address 192.168.32.9
      dns.nameservers 172.34.0.80:53,172.34.0.81:53,172.34.0.82:53
      designate.nameservers 172.34.0.80:53,172.34.0.81:53,172.34.0.82:53
      neutron_plugin_options.dns_domain example.org.
  workflow:
  - stepName: neutron-dns-integration-testing
    tempestRun:
      concurrency: 1
      includeList: |
        #^neutron_tempest_plugin.scenario.test_dns_integration
        ^neutron_tempest_plugin.scenario.test_internal_dns
      extraImages:
      - ID: 11111111-1111-1111-1111-111111111111
        URL: http://10.0.152.55/dfg-network/custom_neutron_guest_rhel_8.4.qcow2
        containerFormat: '-'
        diskFormat: qcow2
        flavor:
          ID: 22222222-2222-2222-2222-222222222222
          RAM: 1024
          disk: 10
          name: custom_neutron_guest_rhel_8.4
          vcpus: 1
        imageCreationTimeout: 300
        name: custom_neutron_guest_rhel_8.4
      extraRPMs:
      - http://download-01.beak-001.prod.iad2.dc.redhat.com/brewroot/vol/rhel-9/packages/python-pyroute2/0.7.3/2.el9ost/noarch/python3-pyroute2-0.7.3-2.el9ost.noarch.rpm
      - http://download-01.beak-001.prod.iad2.dc.redhat.com/brewroot/vol/rhel-9/packages/scapy/2.5.0/1.el9/noarch/python3-scapy-2.5.0-1.el9.noarch.rpm
      - http://download-01.beak-001.prod.iad2.dc.redhat.com/brewroot/vol/rhel-9/packages/python-whitebox-neutron-tests-tempest/0.9.2/18.0.20250604211120.e67f790.el9osttrunk/noarch/python3-whitebox-neutron-tests-tempest-0.9.2-18.0.20250604211120.e67f790.el9osttrunk.noarch.rpm
