#!/bin/bash
# Generated by Cursor AI Assistant
# https://cursor.sh
#
# Setup script for OpenStack Tempest Test Runner

set -e

echo "====================================="
echo "OpenStack Tempest Test Runner Setup"
echo "====================================="
echo ""

# Check Python version
echo "Checking Python version..."
if ! command -v python3 &> /dev/null; then
    echo "ERROR: Python 3 is not installed"
    exit 1
fi

PYTHON_VERSION=$(python3 --version | cut -d' ' -f2 | cut -d'.' -f1,2)
echo "Found Python $PYTHON_VERSION"

# Check if oc is installed
echo "Checking OpenShift CLI..."
if ! command -v oc &> /dev/null; then
    echo "WARNING: OpenShift CLI (oc) is not installed"
    echo "Please install it from: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/"
    echo ""
else
    echo "Found: $(oc version --client)"
fi

# Create virtual environment (optional but recommended)
read -p "Create a virtual environment? (recommended) [Y/n]: " create_venv
create_venv=${create_venv:-Y}

if [[ $create_venv =~ ^[Yy]$ ]]; then
    echo "Creating virtual environment..."
    python3 -m venv venv
    source venv/bin/activate
    echo "Virtual environment created and activated"
else
    echo "Skipping virtual environment creation"
fi

# Install dependencies
echo ""
echo "Installing Python dependencies..."
pip install --upgrade pip
pip install -r requirements.txt

echo ""
echo "====================================="
echo "Setup completed successfully!"
echo "====================================="
echo ""
echo "Next steps:"
echo "1. Edit config.yaml to match your environment"
echo "2. Update CR files (cr_designate_test*.yaml) with your test specifications"
echo "3. Ensure you're logged into OpenShift: oc login <cluster-url>"
echo "4. Run the test runner: python main.py"
echo ""
if [[ $create_venv =~ ^[Yy]$ ]]; then
    echo "Note: Activate the virtual environment with: source venv/bin/activate"
fi
echo ""

